command:
  - bash
  - -c
  - |
      uvicorn backend.app:app \
        --host 0.0.0.0 \
        --port=$PORT \
        --workers 1 \
        --timeout-keep-alive 600

env:
  - name: OPEN_AI_API_KEY
    valueFrom: OPEN_AI_API_KEY

  - name: OPEN_AI_MODEL
    valueFrom: OPEN_AI_MODEL

  - name: OPEN_AI_ENDPOINT
    valueFrom: OPEN_AI_ENDPOINT

  - name: AZURE_STORAGE_ACCOUNT
    valueFrom: AZURE_STORAGE_ACCOUNT

  - name: ACCOUNT_KEY
    valueFrom: ACCOUNT_KEY

  - name: AZURE_BLOB_CONTAINER
    valueFrom: AZURE_BLOB_CONTAINER

  - name: AZURE_STORAGE_CONNECTION_STRING
    valueFrom: AZURE_STORAGE_CONNECTION_STRING

  - name: GOOGLE_DRIVE_SA_JSON
    valueFrom: GOOGLE_DRIVE_SA_JSON

  - name: DRIVE_FOLDER_ID
  valueFrom: DRIVE_FOLDER_ID
